apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: podrequests.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                podName:
                  type: string
                imageName:
                  type: string
                port:
                  type: integer
  scope: Namespaced
  names:
    plural: podrequests
    singular: podrequest
    kind: PodRequest
    shortNames:
      - pr
