apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubernetes-client.serviceAccountName" . }}
automountServiceAccountToken: true

{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kubernetes-client.fullname" . }}
  labels:
    {{- include "kubernetes-client.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["*"]
  - apiGroups: ["example.com"]
    resources: ["podrequests"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubernetes-client.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubernetes-client.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubernetes-client.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
